Repository aionnetwork/aion, pull requests merged in 2018-09, with the labels that each got.

#592 Refactoring - PoW Separation of concerns
  .gitignore
  modAion/build.xml
  modAion/module-info.java
  modAion/src/org/aion/zero/blockchain/IPowChain.java
  modAion/src/org/aion/zero/db/IBlockStorePow.java
  modAion/src/org/aion/zero/types/A0BlockHeader.java
  modAion/src/org/aion/zero/types/IAionBlock.java
  modAionBase/src/org/aion/base/type/IBlock.java
  modAionBase/src/org/aion/base/type/IBlockHeader.java
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionFactory.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/ChainConfiguration.java
  modAionImpl/src/org/aion/zero/impl/blockchain/IAionChain.java
  modAionImpl/src/org/aion/zero/impl/blockchain/IChainInstancePOW.java
  modAionImpl/src/org/aion/zero/impl/core/DiffCalc.java
  modAionImpl/src/org/aion/zero/impl/core/IAionBlockchain.java
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
  modAionImpl/src/org/aion/zero/impl/valid/AionDifficultyRule.java
  modAionImpl/test/org/aion/zero/impl/core/OriginalDifficultyFunctionTest.java
  modApiServer/src/org/aion/api/server/ApiAion.java
  modApiServer/src/org/aion/api/server/pb/ApiAion0.java
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modBoot/src/org/aion/Aion.java
  modMcf/src/org/aion/mcf/blockchain/IChainCfg.java
  modMcf/src/org/aion/mcf/blockchain/IChainInstancePOW.java
  modMcf/src/org/aion/mcf/blockchain/IGenericChain.java
  modMcf/src/org/aion/mcf/blockchain/IPoWChainCfg.java
  modMcf/src/org/aion/mcf/core/IBlockchain.java
  modMcf/src/org/aion/mcf/core/IDifficultyCalculator.java
  modMcf/src/org/aion/mcf/db/AbstractPowBlockstore.java
  modMcf/src/org/aion/mcf/evt/EventHub.java
  modMcf/src/org/aion/mcf/evt/EvtCb.java
  modMcf/src/org/aion/mcf/evt/IPowListener.java
  modMcf/src/org/aion/mcf/types/AbstractBlockHeader.java
  modMcf/src/org/aion/mcf/types/IPowBlockHeader.java
Labels: wip

#589 APB - 46 Precompiled contract to allow ED25519 signature verification
  modPrecompiled/src/org/aion/precompiled/ContractFactory.java
  modPrecompiled/src/org/aion/precompiled/contracts/EDVerifyContract.java
  modPrecompiled/test/org/aion/precompiled/contracts/EDVerifyContractTest.java
Labels: feature, wip

#637 Persistent mock database
  modDbImpl/src/org/aion/db/impl/DBVendor.java
  modDbImpl/src/org/aion/db/impl/DatabaseFactory.java
  modDbImpl/src/org/aion/db/impl/mockdb/MockDB.java
  modDbImpl/src/org/aion/db/impl/mockdb/PersistentMockDB.java
  modDbImpl/test/org/aion/db/impl/DatabaseFactoryTest.java
  modDbImpl/test/org/aion/db/impl/DriverBaseTest.java
Labels: feature

#639 fix p2p-in spin
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskInbound.java
Labels: bug

#640 Monitoring system
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
Labels: enhancement

#646 Put Zero address if no from address supplied
  modAion/src/org/aion/zero/types/AionTransaction.java
  modAionBase/src/org/aion/base/type/Address.java
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionImpl.java
  modApiServer/src/org/aion/api/server/ApiAion.java
  modPrecompiled/src/org/aion/precompiled/contracts/AionAuctionContract.java
  modPrecompiled/src/org/aion/precompiled/contracts/AionNameServiceContract.java
Labels: bug
