Repository aionnetwork/aion, pull requests merged in 2018-11, with the labels that each got.

#697 Block propagation enhancement
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/BlockPropagationHandler.java
  modMcf/src/org/aion/mcf/core/ImportResult.java
Labels: bug, enhancement

#694 Expanded sync statistics
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncMgr.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ReqBlocksBodiesHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResStatusHandler.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: enhancement

#702 Compact the state after slow block imports
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
Labels: enhancement

#700 Enabling choice of stats display from config file
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncMgr.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modBoot/resource/conquest/config.xml
  modBoot/resource/custom/config.xml
  modBoot/resource/mainnet/config.xml
  modBoot/resource/mastery/config.xml
  modMcf/src/org/aion/mcf/config/CfgSync.java
  modMcf/src/org/aion/mcf/config/StatsType.java
Labels: enhancement

#708 Add a test to modApiServer
  modApiServer/build.gradle
  modApiServer/src/org/aion/api/server/ApiAion.java
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modApiServer/src/org/aion/api/server/types/ArgTxCall.java
  modApiServer/test/org/aion/api/server/ApiUtilTest.java
  modApiServer/test/org/aion/api/server/pb/ApiAion0Test.java
  modApiServer/test/org/aion/api/server/types/ArgTxCallTest.java
Labels: enhancement

#713 Support "pending" option for Web3 requests
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modApiServer/test/org/aion/api/server/ApiAionTest.java
  modApiServer/test/org/aion/api/server/rpc/ApiWeb3AionTest.java
Labels: enhancement

#714 Stats enhancements
  modAionImpl/src/org/aion/zero/impl/sync/RequestCounter.java
  modAionImpl/src/org/aion/zero/impl/sync/RequestType.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncMgr.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetBodies.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetHeaders.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResBlocksBodiesHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResStatusHandler.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: bug, enhancement

#718 Config migration
  modAionImpl/src/org/aion/zero/impl/config/CfgAion.java
  modAionImpl/test/org/aion/zero/impl/cli/CliTest.java
  modBoot/src/org/aion/Aion.java
  modMcf/src/org/aion/mcf/config/Cfg.java
Labels: enhancement

#719 Move modBoost/resource to config
  .gitignore
  config/conquest/config.xml
  config/conquest/genesis.json
  config/custom/config.xml
  config/custom/fork.properties
  config/custom/genesis.json
  config/mainnet/config.xml
  config/mainnet/fork.properties
  config/mainnet/genesis.json
  config/mastery/config.xml
  config/mastery/fork.properties
  config/mastery/genesis.json
  script/prepack.sh
Labels: enhancement

#722 Add a missing import to modApiServer's module-info
  modApiServer/src/module-info.java
Labels: bug

#727 Removed lib from aion.sh
  aion.sh
  build.gradle
Labels: bug

#726 Update DOCKER.md
  DOCKER.md
Labels: document change

#729 Fix docker, aion.sh file and documentation
  DOCKER.md
  aion-docker.sh
  aion.sh
  build.gradle
  create-coinbase.sh
  override-config.py
Labels: bug

#730 move genesis to new location for custom networks
  modMcf/src/org/aion/mcf/config/Cfg.java
Labels: bug

#738 Correcting some tests
  build.gradle
  modMcf/test/org/aion/mcf/config/CfgLogTest.java
Labels: bug
