Repository aionnetwork/aion, pull requests merged in 2018-06, with the labels that each got.

#487 Refactoring the public TD management
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/StandaloneBlockchain.java
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/BlockPropagationHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ReqStatusHandler.java
  modAionImpl/src/org/aion/zero/impl/types/AionBlock.java
  modAionImpl/test/org/aion/zero/impl/GenesisSpecificationTest.java
Labels: enhancement

#478 Enabling JournalPruneDataSource
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/db/RecoveryUtils.java
  modAionImpl/test/org/aion/zero/impl/BlockchainDataRecoveryTest.java
  modAionImpl/test/org/aion/zero/impl/db/AionRepositoryImplTest.java
  modBoot/resource/config.xml
  modMcf/src/org/aion/mcf/config/CfgDb.java
  modMcf/src/org/aion/mcf/db/AbstractRepository.java
  modMcf/src/org/aion/mcf/db/DetailsDataStore.java
  modMcf/src/org/aion/mcf/trie/Cache.java
  modMcf/src/org/aion/mcf/trie/JournalPruneDataSource.java
  modMcf/src/org/aion/mcf/trie/Trie.java
  modMcf/src/org/aion/mcf/trie/TrieImpl.java
  modMcf/test/org/aion/trie/JournalPruneDataSourceTest.java
Labels: enhancement

#482 Refactor and test journal pruning class
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modMcf/src/org/aion/mcf/db/AbstractRepository.java
  modMcf/src/org/aion/mcf/db/DetailsDataStore.java
  modMcf/src/org/aion/mcf/trie/JournalPruneDataSource.java
  modMcf/test/org/aion/mcf/trie/JournalPruneDataSourceTest.java
  modMcf/test/org/aion/trie/JournalPruneDataSourceTest.java
Labels: enhancement

#508 Add enhancement box to PR template
  .github/pull_request_template.md
Labels: document change

#514 fixing the bug introduced by the different branch merges
  modAionImpl/src/org/aion/zero/impl/AionHubUtils.java
  modAionImpl/src/org/aion/zero/impl/StandaloneBlockchain.java
  modAionImpl/test/org/aion/zero/impl/BlockchainDataRecoveryTest.java
Labels: bug

#502 Enhanced logger
  modApiServer/src/org/aion/api/server/Api.java
  modBoot/resource/config.xml
  modBoot/src/org/aion/Aion.java
  modLogger/src/org/aion/log/AionLoggerFactory.java
  modMcf/src/org/aion/mcf/config/CfgLog.java
  modMcf/test/org/aion/mcf/config/CfgLogTest.java
Labels: enhancement

#521 fix missing p2p-outbound-lane
  modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
Labels: bug

#515 P2p outbound
  modAionImpl/test/org/aion/zero/impl/sync/BlockPropagationTest.java
  modP2p/src/org/aion/p2p/INodeMgr.java
  modP2p/src/org/aion/p2p/IP2pMgr.java
  modP2pImpl/src/org/aion/p2p/impl/comm/NodeMgr.java
  modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/ChannelBuffer.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/MsgIn.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/MsgOut.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskClear.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskConnectPeers.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskInbound.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskReceive.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskSend.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskStatus.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskWrite.java
  modP2pImpl/test/org/aion/p2p/impl/Test.java
Labels: enhancement

#505 properly shutdown zmq socket
  modAionImpl/src/org/aion/zero/impl/sync/handler/BroadcastTxHandler.java
  modApiServer/src/org/aion/api/server/zmq/ProtocolProcessor.java
  modApiServer/src/org/aion/api/server/zmq/Proxy.java
Labels: bug

#501 Dev redis q2
  lib/commons-pool2-2.0.jar
  lib/jedis-2.9.0.jar
  modDbImpl/build.xml
  modDbImpl/module-info.java
  modDbImpl/src/org/aion/db/impl/DBConstants.java
  modDbImpl/src/org/aion/db/impl/DBVendor.java
  modDbImpl/src/org/aion/db/impl/DatabaseFactory.java
  modDbImpl/src/org/aion/db/impl/redisdb/RedisClusterConstants.java
  modDbImpl/src/org/aion/db/impl/redisdb/RedisClusterWrapper.java
  modDbImpl/src/org/aion/db/impl/redisdb/RedisConstants.java
  modDbImpl/src/org/aion/db/impl/redisdb/RedisWrapper.java
Labels: enhancement

#532 Improved bootup integrity check
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
Labels: enhancement

#531 AionBlockchainImpl unit tests and minor bug fixes
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/StandaloneBlockchain.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ReqBlocksHeadersHandler.java
  modAionImpl/test/org/aion/zero/impl/BlockchainConcurrentImportTest.java
  modAionImpl/test/org/aion/zero/impl/BlockchainDataRecoveryTest.java
  modAionImpl/test/org/aion/zero/impl/BlockchainImplementationTest.java
  modAionImpl/test/org/aion/zero/impl/BlockchainTestUtils.java
  modAionImpl/test/org/aion/zero/impl/MockRepositoryConfig.java
  modMcf/src/org/aion/mcf/core/IBlockchain.java
Labels: enhancement
