Repository aionnetwork/aion, pull requests merged in 2018-10, with the labels that each got.

#635 Sync enhancement: first version of Lightning sync
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/db/PendingBlockStore.java
  modAionImpl/src/org/aion/zero/impl/sync/PeerState.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncMgr.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStatics.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetBodies.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetHeaders.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/BlockPropagationHandler.java
  modAionImpl/src/org/aion/zero/impl/types/AionBlock.java
  modAionImpl/test/org/aion/util/TestResources.java
  modAionImpl/test/org/aion/zero/impl/BlockchainTestUtils.java
  modAionImpl/test/org/aion/zero/impl/db/PendingBlockStoreTest.java
  modAionImpl/test/org/aion/zero/impl/sync/TaskImportBlocksTest.java
  modDbImpl/src/org/aion/db/impl/DatabaseFactory.java
  modDbImpl/src/org/aion/db/impl/mockdb/PersistentMockDB.java
  modMcf/src/org/aion/mcf/config/CfgDb.java
  modMcf/src/org/aion/mcf/core/IBlockchain.java
  modMcf/src/org/aion/mcf/core/ImportResult.java
  modMcf/src/org/aion/mcf/db/AbstractRepository.java
  modMcf/src/org/aion/mcf/db/DatabaseUtils.java
  modMcf/src/org/aion/mcf/ds/ObjectDataSource.java
  modP2p/src/org/aion/p2p/P2pConstant.java
Labels: enhancement, feature

#609 Checksum
  modCrypto/src/org/aion/crypto/AddressSpecs.java
  modCrypto/test/org/aion/crypto/ChecksumTest.java
Labels: enhancement

#650 CLI refactoring
  modAionImpl/build.gradle
  modAionImpl/build.xml
  modAionImpl/src/org/aion/zero/impl/cli/Arguments.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/config/CfgAion.java
  modAionImpl/src/org/aion/zero/impl/config/Network.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/test/org/aion/cli/CliTest.java
  modAionImpl/test/org/aion/util/TestResources.java
  modAionImpl/test/org/aion/zero/impl/GenesisTestNetJsonTest.java
  modAionImpl/test/org/aion/zero/impl/cli/ArgumentsTest.java
  modAionImpl/test/org/aion/zero/impl/cli/CliTest.java
  modAionImpl/test/org/aion/zero/impl/config/NetworkTest.java
  modAionImpl/test_resources/config.xml
  modAionImpl/test_resources/genesis.json
  modAionImpl/test_resources/testnet.json
  modBoot/resource/conquest/genesis.json
  modBoot/resource/custom/config.xml
  modBoot/resource/custom/genesis.json
  modBoot/resource/mastery/config.xml
  modBoot/resource/mastery/genesis.json
  modBoot/src/org/aion/Aion.java
  modMcf/src/org/aion/mcf/config/Cfg.java
  modMcf/src/org/aion/mcf/config/CfgLog.java
Labels: enhancement, feature

#659 Gradle improvements
  .gitignore
  aion_gui.sh
  build.gradle
  build.xml
  modAion/build.xml
  modAionBase/build.xml
  modAionImpl/build.gradle
  modAionImpl/build.xml
  modApiServer/build.gradle
  modApiServer/build.xml
  modApiServer/src/module-info.java
  modBoot/build.gradle
  modBoot/build.xml
  modBoot/src/module-info.java
  modCrypto/build.xml
  modDbImpl/build.xml
  modEvtMgr/build.xml
  modEvtMgrImpl/build.xml
  modGui/build.gradle
  modGui/build.xml
  modGui/src/module-info.java
  modLogger/build.xml
  modMcf/build.xml
  modP2p/build.xml
  modP2pImpl/build.xml
  modPrecompiled/build.xml
  modRlp/build.xml
  modTxPool/build.gradle
  modTxPool/build.xml
  modTxPool/src/org/aion/txpool/TxPoolModule.java
  modTxPoolImpl/build.xml
  modTxPoolImpl/src/module-info.java
  modVM/build.xml
  settings.gradle
Labels: bug, enhancement

#662 Impoved messaging for lightning sync
  modAionImpl/src/org/aion/zero/impl/sync/PeerState.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
Labels: enhancement

#656 fix TxReceiptLog address issue
  modApiServer/src/org/aion/api/server/types/TxRecptLg.java
Labels: bug

#663 Sync: Enhanced TaskImportBlocks
  modAionImpl/src/org/aion/zero/impl/db/PendingBlockStore.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskDropImportedBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskStorePendingBlocks.java
Labels: enhancement

#683 Ensuring that exceptions in the PendingBlockStore do not hamper sync
  modAionImpl/src/org/aion/zero/impl/db/PendingBlockStore.java
  modAionImpl/test/org/aion/zero/impl/db/PendingBlockStoreTest.java
Labels: bug

#684 Replace (most) instances of "catch Throwable" with "catch Exception"
  modAionBase/src/org/aion/base/util/ExecutorPipeline.java
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionPendingStateImpl.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/BroadcastTxHandler.java
  modAionImpl/test/org/aion/zero/impl/BlockchainAccountStateBenchmark.java
  modAionImpl/test/org/aion/zero/impl/BlockchainConcurrentImportTest.java
  modApiServer/src/org/aion/api/server/IApiAion.java
  modApiServer/src/org/aion/api/server/pb/ApiAion0.java
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modApiServer/src/org/aion/api/server/zmq/HdlrZmq.java
  modDbImpl/test/org/aion/db/impl/DatabaseTestUtils.java
  modEvtMgr/src/org/aion/evtmgr/EventMgrModule.java
  modEvtMgr/test/org/aion/evtmgr/EventMgrModuleTest.java
  modEvtMgrImpl/src/org/aion/evtmgr/impl/abs/AbstractHandler.java
  modGui/test/org/aion/os/UnixProcessTerminatorTest.java
  modGui/test/org/aion/wallet/account/AccountManagerTest.java
  modMcf/src/org/aion/mcf/tx/AbstractTxTask.java
  modMcf/test/org/aion/mcf/trie/JournalPruneDataSourceTest.java
  modP2pImpl/src/org/aion/p2p/impl2/TaskWrite.java
  modTxPool/src/org/aion/txpool/TxPoolModule.java
  modTxPoolImpl/test/org/aion/txpool/test/TxnPoolTest.java
Labels: enhancement

#688 Preemptive measures for exceptions and correct for repository snapshots
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
Labels: bug, enhancement
