Repository aionnetwork/aion, pull requests merged in 2018-12, with the labels that each got.

#742 Cleaning up directories after test execution
  modAionImpl/test/org/aion/zero/impl/cli/CliTest.java
  modApiServer/test/org/aion/api/server/pb/ApiAion0Test.java
Labels: bug

#736 Cli port input
  modAionImpl/src/org/aion/zero/impl/cli/Arguments.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/config/CfgAion.java
  modAionImpl/test/org/aion/zero/impl/cli/CliTest.java
  modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
Labels: feature

#744 Isolate modGui and its build logic
  build.gradle
  gradle.properties
  modGui/aion_gui.sh
  modGui/build.gradle
  script/prepack.sh
  settings.gradle
Labels: enhancement

#762 Quickfix for estimating gas of contract creation txs
  modApiServer/src/org/aion/api/server/ApiAion.java
Labels: bug
