Repository aionnetwork/aion, pull requests merged in 2019-11, with the labels that each got.

#1057 AKI-450: updated ContractIntegTest energy tests for Unity
  modAionImpl/test/org/aion/zero/impl/vm/ContractIntegTest.java
Labels: unit tests

#1064 AKI-509: Bugfix for block encoding/decoding inconsistency:
  modAionImpl/src/org/aion/zero/impl/types/AbstractBlock.java
  modAionImpl/src/org/aion/zero/impl/types/AionBlock.java
  modAionImpl/src/org/aion/zero/impl/types/StakingBlock.java
Labels: bug, unit tests

#1066 Unit tests for encode/decode staking & mining blocks
  modAionImpl/test/org/aion/zero/impl/types/BlockEncodeTest.java
Labels: unit tests

#1067 AKI-451: Test for re-branching after Unity fork
  lib/modAvmVersion1.jar
  lib/modAvmVersion2.jar
  modAionImpl/src/org/aion/zero/impl/blockchain/StandaloneBlockchain.java
  modAionImpl/test/org/aion/zero/impl/blockchain/BlockchainForkingTest.java
  modAionImpl/test/org/aion/zero/impl/blockchain/BlockchainTestUtils.java
  modAvmStub/src/org/aion/avm/stub/IStreamingEncoder.java
  modAvmVersion1/src/org/aion/avm/version1/StreamingEncoder.java
  modAvmVersion2/src/org/aion/avm/version2/StreamingEncoder.java
Labels: unit tests

#1070 AKI-544 fix bootlist nodes has been remove on the tempNode list after…
  modP2pImpl/src/org/aion/p2p/impl/comm/NodeMgr.java
Labels: bug

#1073 AKI-553 fixed get event logs skip the contract created transaction
  modApiServer/src/org/aion/api/server/types/FltrLg.java
Labels: bug

#1074 Filtered out POS blocks from the minerStatsView data store[AKI-513].
  modApiServer/src/org/aion/api/server/ApiAion.java
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
Labels: bug
