Repository aionnetwork/aion, pull requests merged in 2019-03, with the labels that each got.

#841 Docker/Jenkins - build image for distribution and Kubernetes
  DOCKER.md
  DockerAutomation/Dockerfile
  DockerAutomation/Jenkinsfile
  DockerAutomation/bin/enable-api-servers.py
  DockerAutomation/k8s/Dockerfile
  DockerAutomation/k8s/Jenkinsfile
  DockerAutomation/k8s/aion_node.yaml
  DockerAutomation/k8s/aion_seed.yaml
  DockerAutomation/k8s/custom/config/config.xml
  DockerAutomation/k8s/custom/config/fork.properties
  DockerAutomation/k8s/custom/config/genesis.json
  DockerAutomation/k8s/custom/keystore/UTC--2018-10-02T18:56:56.324Z--a037818674c51fafbb1da0656dd467076d6a00552e13dfb1137d3ca6f288b65f
  DockerAutomation/k8s/custom/keystore/UTC--2018-10-02T18:57:16.584Z--a006ece379f27a301edd3e58feeca9847dc00f682c379fc9711929c0ca7e3835
  DockerAutomation/k8s/custom/keystore/UTC--2018-10-02T18:57:31.755Z--a06750add06961701f2e596681823de1b8fb116b3606bcae97e3f2b8feb52fdb
  DockerAutomation/k8s/deploy.py
  DockerAutomation/k8s/find_endpoint.py
  DockerAutomation/k8s/list_deployments.py
  DockerAutomation/k8s/list_image.py
  DockerAutomation/k8s/modify_config.py
  DockerAutomation/k8s/monitor_sync.py
  DockerAutomation/k8s/redeploy.py
  DockerAutomation/k8s/requirements.txt
  DockerAutomation/k8s/seedStorage.yaml
  DockerAutomation/k8s/service.yaml
  Dockerfile
  README.md
  build.gradle
  override-config.py
Labels: build script

#842 Rearchitect repo
  modAionImpl/build.gradle
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/test/org/aion/db/AionContractDetailsTest.java
  modAionImpl/test/org/aion/zero/impl/BlockchainAccountStateBenchmark.java
  modDbImpl/src/module-info.java
  modMcf/build.gradle
  modMcf/src/org/aion/mcf/trie/TrieImpl.java
  modRlp/src/main/java/org/aion/rlp/Value.java
Labels: enhancement

#843 add handling for the vm fatal status
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionPendingStateImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/test/org/aion/zero/impl/vm/Benchmark.java
  modAionImpl/test/org/aion/zero/impl/vm/ContractIntegTest.java
  modAionImpl/test/org/aion/zero/impl/vm/InternalTransactionTest.java
  modAionImpl/test/org/aion/zero/impl/vm/OldTxExecutorTest.java
  modAionImpl/test/org/aion/zero/impl/vm/OpcodeIntegTest.java
  modAionImpl/test/org/aion/zero/impl/vm/SolidityTypeTest.java
  modAionImpl/test/org/aion/zero/impl/vm/TransactionExecutorTest.java
  modMcf/src/org/aion/mcf/db/ContractDetailsCacheImpl.java
  modVM/src/module-info.java
  modVM/src/org/aion/vm/BulkExecutor.java
  modVM/src/org/aion/vm/exception/VMException.java
Labels: bug

#846 Small Refactoring in repo, trie and rlp
  modAion/src/org/aion/zero/db/AionRepositoryCache.java
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modMcf/src/org/aion/mcf/trie/TrieImpl.java
  modMcf/src/org/aion/mcf/vm/types/Bloom.java
  modRlp/src/main/java/org/aion/rlp/RLP.java
  modVM/src/org/aion/vm/BulkExecutor.java
  modVM/src/org/aion/vm/ExecutionBatch.java
Labels: enhancement

#850 DockerAutomation Jenkinsfile bugfixes: typos in filename and image name
  DockerAutomation/Jenkinsfile
  DockerAutomation/k8s/Dockerfile
  DockerAutomation/k8s/Jenkinsfile
Labels: bug, build script

#848 Avm now handles "pure" balance transfers
  modAionImpl/test/org/aion/zero/impl/consensus/BalanceTransferConsensusTest.java
  modAionImpl/test/org/aion/zero/impl/consensus/ConsensusTest.java
  modAionImpl/test/org/aion/zero/impl/consensus/FvmBalanceTransferConsensusTest.java
  modAionImpl/test/org/aion/zero/impl/vm/contracts/NonpayableConstructor.sol
  modAionImpl/test/org/aion/zero/impl/vm/contracts/NonpayableFallbackContract.sol
  modAionImpl/test/org/aion/zero/impl/vm/contracts/PayableConstructor.sol
  modAionImpl/test/org/aion/zero/impl/vm/contracts/PayableContract.sol
  modAionImpl/test/org/aion/zero/impl/vm/contracts/PayableFallbackContract.sol
  modVM/src/org/aion/vm/BulkExecutor.java
Labels: feature, unit tests

#844 Sync stats expansion & refactor
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetBodies.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetHeaders.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskStorePendingBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/BlockPropagationHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResBlocksBodiesHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResBlocksHeadersHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResStatusHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/BlockType.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/RequestCounter.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/RequestStatsTracker.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/RequestType.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/ResponseStatsTracker.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/TopLeechesStatsTracker.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/TopSeedsStatsTracker.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: enhancement, unit tests

#855 Bug fix: using the repositoryChild to check for used VM
  modAionImpl/test/org/aion/zero/impl/PendingStateTest.java
  modVM/src/org/aion/vm/BulkExecutor.java
Labels: bug, unit tests

#847 Blocks transfer functionality for fast sync
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/SystemExitCodes.java
  modAionImpl/src/org/aion/zero/impl/core/IAionBlockchain.java
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
  modAionImpl/src/org/aion/zero/impl/sync/Act.java
  modAionImpl/src/org/aion/zero/impl/sync/FastSyncManager.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskFastImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskValidateAndAddBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/RequestBlocksHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/RequestTrieDataHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResponseBlocksHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResponseTrieDataHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/msg/RequestBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/msg/RequestTrieData.java
  modAionImpl/src/org/aion/zero/impl/sync/msg/ResponseBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/msg/ResponseTrieData.java
  modAionImpl/src/org/aion/zero/impl/types/AionBlock.java
  modAionImpl/test/org/aion/zero/impl/BlockchainImplementationTest.java
  modAionImpl/test/org/aion/zero/impl/db/AionBlockStoreTest.java
  modAionImpl/test/org/aion/zero/impl/sync/handler/RequestBlocksHandlerTest.java
  modAionImpl/test/org/aion/zero/impl/sync/handler/RequestTrieDataHandlerTest.java
  modAionImpl/test/org/aion/zero/impl/sync/handler/ResponseBlocksHandlerTest.java
  modAionImpl/test/org/aion/zero/impl/sync/handler/ResponseTrieDataHandlerTest.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/RequestBlocksTest.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/RequestTrieDataTest.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/ResponseBlocksTest.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/ResponseTrieDataTest.java
  modMcf/src/org/aion/mcf/core/FastImportResult.java
  modP2p/src/org/aion/p2p/V1Constants.java
  modP2p/src/org/aion/p2p/Ver.java
Labels: enhancement, feature, unit tests

#859 Removed the unnecessary MIN_NORMAL_PEERS restriction
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/test/org/aion/zero/impl/sync/TaskImportBlocksTest.java
  modP2p/src/org/aion/p2p/P2pConstant.java
Labels: enhancement

#858 Correct check for contracts to include precompiled contracts
  modAionImpl/test/org/aion/zero/impl/consensus/FvmBalanceTransferConsensusTest.java
  modVM/src/org/aion/vm/BulkExecutor.java
Labels: bug, unit tests

#860 Added 'blank-slate' config & genesis for avm testnet
  config/avmtestnet/config-seed1.xml
  config/avmtestnet/config-seed2.xml
  config/avmtestnet/config-seed3.xml
  config/avmtestnet/config.xml
  config/avmtestnet/fork.properties
  config/avmtestnet/genesis.json
Labels: enhancement

#861 Minor repository refactoring
  modAionImpl/src/org/aion/zero/impl/db/AbstractContractDetails.java
  modAionImpl/src/org/aion/zero/impl/db/AbstractRepositoryCache.java
  modAionImpl/src/org/aion/zero/impl/db/AionContractDetailsImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryCache.java
  modAionImpl/src/org/aion/zero/impl/db/ContractDetailsCacheImpl.java
Labels: enhancement
