Repository aionnetwork/aion, pull requests merged in 2019-04, with the labels that each got.

#863 Allow avm executing the balance transfer
  config/avmtestnet/config-seed1.xml
  config/avmtestnet/config-seed2.xml
  config/avmtestnet/config-seed3.xml
  config/avmtestnet/config.xml
  gradle.properties
  lib/org-aion-avm-api.jar
  lib/org-aion-avm-core.jar
  lib/org-aion-avm-rt.jar
  lib/org-aion-avm-userlib.jar
  modAionImpl/build.gradle
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/test/org/aion/zero/impl/PendingStateTest.java
  modAionImpl/test/org/aion/zero/impl/vm/AvmBulkTransactionTest.java
  modAionImpl/test/org/aion/zero/impl/vm/AvmHelloWorldTest.java
  modAionImpl/test/org/aion/zero/impl/vm/InvalidBlockTest.java
  modAionImpl/test/org/aion/zero/impl/vm/StatefulnessTest.java
  modAionImpl/test/org/aion/zero/impl/vm/VMTxStateAlignTest.java
  modAionImpl/test/org/aion/zero/impl/vm/contracts/AvmHelloWorld.java
  modAionImpl/test/org/aion/zero/impl/vm/contracts/Contract.java
  modAionImpl/test/org/aion/zero/impl/vm/contracts/Statefulness.java
  modApiServer/build.gradle
  modApiServer/test/org/aion/api/server/ApiAionTest.java
  modApiServer/test/org/aion/api/server/pb/ApiAion0Test.java
  modBoot/src/org/aion/Aion.java
  modMcf/src/org/aion/mcf/valid/TransactionTypeRule.java
  modVM/src/org/aion/vm/BulkExecutor.java
  modVM/src/org/aion/vm/KernelInterfaceForAVM.java
Labels: feature

#845 Fix to eth_syncing
  modAionImpl/src/org/aion/zero/impl/blockchain/AionImpl.java
  modAionImpl/src/org/aion/zero/impl/query/SyncQueryInterface.java
  modApiServer/src/org/aion/api/server/ApiAion.java
  modApiServer/src/org/aion/api/server/pb/ApiAion0.java
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modApiServer/test/org/aion/api/server/ApiAionTest.java
  modApiServer/test/org/aion/api/server/pb/ApiAion0Test.java
Labels: bug, enhancement

#867 FVM contract encoding update
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/db/AbstractContractDetails.java
  modAionImpl/src/org/aion/zero/impl/db/AionContractDetailsImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/db/ContractDetailsCacheImpl.java
  modAionImpl/test/org/aion/zero/impl/db/AionContractDetailsTest.java
  modMcf/src/org/aion/mcf/ds/XorDataSource.java
Labels: bug, enhancement, unit tests

#869 Test for forking blocks with contract storage updates
  modAionImpl/test/org/aion/zero/impl/BlockchainForkingTest.java
Labels: unit tests

#868 CI: run functional tests for PRs, mpm, master branches
  Jenkinsfile
Labels: build script

#875 Jenkinsfile: put back cleanWs() otherwise, each subsequent run for a …
  Jenkinsfile
Labels: build script

#877 Reduce log level for some tests
  modAionImpl/test/org/aion/zero/impl/BlockchainImplementationTest.java
  modAionImpl/test/org/aion/zero/impl/vm/OldTxExecutorTest.java
Labels: build script

#878 fix vm initialize error due to loadBlockchain in the aionhub
  modBoot/src/org/aion/Aion.java
Labels: bug

#879 Post-fork transaction validation
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionPendingStateImpl.java
  modAionImpl/src/org/aion/zero/impl/valid/TransactionTypeValidator.java
  modAionImpl/test/org/aion/zero/impl/consensus/BalanceTransferConsensusTest.java
  modAionImpl/test/org/aion/zero/impl/vm/AvmBulkTransactionTest.java
  modAionImpl/test/org/aion/zero/impl/vm/FvmBulkTransactionTest.java
  modAionImpl/test/org/aion/zero/impl/vm/InvalidBlockTest.java
  modAionImpl/test/org/aion/zero/impl/vm/StatefulnessTest.java
  modMcf/src/org/aion/mcf/tx/TransactionTypes.java
  modMcf/src/org/aion/mcf/types/AbstractTransaction.java
  modMcf/src/org/aion/mcf/valid/TransactionTypeRule.java
Labels: enhancement, unit tests

#884 CLI option for retrieving data for consensus tests
  modAionImpl/src/org/aion/zero/impl/cli/Arguments.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/db/RecoveryUtils.java
Labels: feature

#885 Additional consensus test for mastery
  .gitattributes
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/StandaloneBlockchain.java
  modAionImpl/test/org/aion/zero/impl/consensus/MasteryConsensusTest.java
  modAionImpl/test_resources/masteryStateAt1023762.txt
  modAionImpl/test_resources/masteryStateAt250717.txt
  modAionImpl/test_resources/masteryStateAt257158.txt
  modAionImpl/test_resources/masteryStateAt449071.txt
  modAionImpl/test_resources/masteryStateAt720106.txt
  modAionImpl/test_resources/masteryStorageAt449071.txt
Labels: bug, unit tests

#882 Add a method that returns the block reward
  modApiServer/src/org/aion/api/server/pb/ApiAion0.java
  modApiServer/src/org/aion/api/server/pb/Message.java
  modApiServer/test/org/aion/api/server/pb/ApiAion0Test.java
Labels: feature

#881 fix p2p taskStatus disappear issue
  modP2pImpl/src/org/aion/p2p/impl/TaskRequestActiveNodes.java
  modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskStatus.java
  modP2pImpl/test/org/aion/p2p/impl1/tasks/TaskStatusTest.java
Labels: bug

#886 Add test cases for the vm type specs
  modAionImpl/test/org/aion/zero/impl/consensus/BalanceTransferConsensusTest.java
  modAionImpl/test/org/aion/zero/impl/vm/AvmHelloWorldTest.java
  modAionImpl/test/org/aion/zero/impl/vm/ContractIntegTest.java
  modAionImpl/test/org/aion/zero/impl/vm/InternalTransactionTest.java
  modAionImpl/test/org/aion/zero/impl/vm/StatefulnessTest.java
  modAionImpl/test/org/aion/zero/impl/vm/contracts/InternalCallContract.sol
Labels: unit tests

#888 tweak fast sync constants for speed increase
  modP2p/src/org/aion/p2p/P2pConstant.java
Labels: enhancement

#887 Revise the module build dependency
  modAion/build.gradle
  modAionImpl/build.gradle
  modApiServer/build.gradle
  modBoot/build.gradle
  modCrypto/build.gradle
  modDbImpl/build.gradle
  modEvtMgr/build.gradle
  modEvtMgrImpl/build.gradle
  modLogger/build.gradle
  modMcf/build.gradle
  modP2pImpl/build.gradle
  modPrecompiled/build.gradle
  modRlp/build.gradle
  modTxPoolImpl/build.gradle
  modVM/build.gradle
Labels: enhancement

#890 Add a test for internal transactions in the AVM
  modAionImpl/test/org/aion/zero/impl/vm/AvmInternalTxTest.java
  modAionImpl/test/org/aion/zero/impl/vm/contracts/AvmInternalTx.java
Labels: enhancement

#891 Minor fix to new test
  modAionImpl/test/org/aion/zero/impl/vm/AvmInternalTxTest.java
Labels: bug
