Repository aionnetwork/aion, pull requests merged in 2019-10, with the labels that each got.

#1003 AKI-317
  modAionImpl/src/org/aion/zero/impl/db/AionTransactionStoreSerializer.java
  modAionImpl/src/org/aion/zero/impl/types/AionTxInfo.java
Labels: enhancement

#1002 Revert "Random port assignment in NodeMgrTest"
  modP2pImpl/test/org/aion/p2p/impl/comm/NodeMgrTest.java
Labels: unit tests

#1007 Fully removed heap cache setting from config
  modAionImpl/src/org/aion/zero/impl/db/DBUtils.java
  modMcf/src/org/aion/mcf/config/CfgDb.java
  modMcf/src/org/aion/mcf/config/CfgDbDetails.java
Labels: enhancement

#1010 Removed implementation of DatabaseWithCache
  modAionImpl/src/org/aion/zero/impl/blockchain/StandaloneBlockchain.java
  modAionImpl/test/org/aion/zero/impl/db/AionContractDetailsTest.java
  modAionImpl/test/org/aion/zero/impl/db/AionRepositoryCacheTest.java
  modAionImpl/test/org/aion/zero/impl/db/AionRepositoryImplTest.java
  modAionImpl/test/org/aion/zero/impl/db/MockRepositoryConfig.java
  modAionImpl/test/org/aion/zero/impl/sync/TaskImportBlocksTest.java
  modDbImpl/src/org/aion/db/generic/DatabaseWithCache.java
  modDbImpl/src/org/aion/db/impl/DatabaseFactory.java
  modDbImpl/test/org/aion/db/impl/DatabaseFactoryTest.java
  modDbImpl/test/org/aion/db/impl/DatabaseTestUtils.java
  modDbImpl/test/org/aion/db/impl/DriverBaseTest.java
  modMcf/src/org/aion/mcf/config/CfgDb.java
  modMcf/src/org/aion/mcf/config/CfgDbDetails.java
  modPrecompiled/test/org/aion/precompiled/ExternalStateForTests.java
  modPrecompiled/test/org/aion/precompiled/contracts/ATB/BridgeTransferTest.java
  modPrecompiled/test/org/aion/precompiled/contracts/ATB/TokenBridgeContractTest.java
  modPrecompiled/test/org/aion/precompiled/contracts/TotalCurrencyContractTest.java
Labels: enhancement, unit tests

#1020 PR instructions as comments
  .github/pull_request_template.md
Labels: document change

#1026 AKI-437 Fix gradle build jar dependency
  build.gradle
Labels: bug

#1030 Predefined StakerRegistry contract
  build.gradle
  lib/modAvmVersion1.jar
  lib/modAvmVersion2.jar
  lib/org-aion-avm-tooling-v1.jar
  lib/org-aion-avm-tooling-v2.jar
  modAionImpl/src/org/aion/zero/impl/vm/avm/internal/AvmDependencyInfo.java
  modAionImpl/src/org/aion/zero/impl/vm/avm/internal/AvmResourcesVersion1.java
  modAionImpl/src/org/aion/zero/impl/vm/avm/internal/AvmResourcesVersion2.java
  modAionImpl/test/org/aion/zero/impl/vm/TestResourceProvider.java
  modAvmStub/src/org/aion/avm/stub/IContractFactory.java
  modAvmVersion1/build.gradle
  modAvmVersion1/src/module-info.java
  modAvmVersion1/src/org/aion/avm/version1/AvmResourceFactory.java
  modAvmVersion1/src/org/aion/avm/version1/ContractFactory.java
  modAvmVersion1/src/org/aion/avm/version1/contracts/unity/StakerRegistry.java
  modAvmVersion1/src/org/aion/avm/version1/contracts/unity/StakerRegistryEvents.java
  modAvmVersion1/src/org/aion/avm/version1/contracts/unity/StakerRegistryStorage.java
  modAvmVersion1/src/org/aion/avm/version1/contracts/unity/StakerStorageObjects.java
  modAvmVersion2/build.gradle
  modAvmVersion2/src/module-info.java
  modAvmVersion2/src/org/aion/avm/version2/AvmResourceFactory.java
Labels: enhancement

#1028 Added system resources log
  config/amity/config.xml
  config/custom/config.xml
  config/mainnet/config.xml
  modAionImpl/src/org/aion/zero/impl/config/StatsType.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
Labels: enhancement

#1037 AKI-454: Simplified AionRepositoryCache locking
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryCache.java
Labels: enhancement

#1042 AKI-428: 10x speed up for --revert operation
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
Labels: enhancement

#1051 Reduced AVM overlap to 0 blocks to avoid AVM caching issues
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/test/org/aion/zero/impl/blockchain/Avm2ForkingTest.java
  modBoot/src/org/aion/Aion.java
Labels: bug

#1053 Update self node into the peer info
  modAionImpl/src/org/aion/zero/impl/blockchain/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionHub.java
  modAionImpl/test/org/aion/zero/impl/sync/BlockPropagationTest.java
  modP2p/src/org/aion/p2p/INodeMgr.java
  modP2p/src/org/aion/p2p/IP2pMgr.java
  modP2pImpl/src/org/aion/p2p/impl/comm/NodeMgr.java
  modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
  modP2pImpl/test/org/aion/p2p/impl/comm/NodeMgrTest.java
Labels: enhancement
