Repository aionnetwork/aion, pull requests merged in 2019-02, with the labels that each got.

#793 Slight rework, added link to docs repo
  .github/issue_template.md
Labels: document change

#800 Helper CLI for checking consensus
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/StandaloneBlockchain.java
  modAionImpl/src/org/aion/zero/impl/cli/Arguments.java
  modAionImpl/src/org/aion/zero/impl/cli/Cli.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/db/RecoveryUtils.java
  modMcf/src/org/aion/mcf/config/CfgDb.java
Labels: feature

#805 Allowing 0 as a transaction type for the FVM
  modAionBase/src/org/aion/base/vm/VirtualMachineSpecs.java
  modMcf/src/org/aion/mcf/valid/TransactionTypeRule.java
Labels: bug

#807 correctly handling the compact during sync config setting
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
Labels: bug

#813 Cleaning up some trie functionality
  modAion/src/org/aion/zero/db/AionContractDetailsImpl.java
  modMcf/src/org/aion/mcf/trie/Cache.java
  modMcf/src/org/aion/mcf/trie/SecureTrie.java
  modMcf/src/org/aion/mcf/trie/Trie.java
  modMcf/src/org/aion/mcf/trie/TrieImpl.java
  modMcf/src/org/aion/mcf/trie/TrieIterator.java
  modMcf/test/org/aion/mcf/trie/TrieTest.java
  modMcf/test/org/aion/mcf/trie/TrieTestWithRootHashValues.java
Labels: enhancement

#814 Sync State 1: Messages for trie data requests/responses
  modAionImpl/src/org/aion/zero/impl/sync/Act.java
  modAionImpl/src/org/aion/zero/impl/sync/DatabaseType.java
  modAionImpl/src/org/aion/zero/impl/sync/msg/RequestTrieData.java
  modAionImpl/src/org/aion/zero/impl/sync/msg/ResponseTrieData.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/RequestTrieDataTest.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/ResponseTrieDataTest.java
  modP2p/src/org/aion/p2p/V1Constants.java
  modP2p/src/org/aion/p2p/Ver.java
  modP2pImpl/src/org/aion/p2p/impl/one/msg/Hello.java
Labels: feature

#819 Allow solidity zip compilation over web3
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modApiServer/src/org/aion/api/server/rpc/RpcMethods.java
Labels: enhancement

#822 Fix ZMQ Wrapper key pair generation bug
  3rdParty/libnzmq/src/org/zeromq/NativeZmqLoader.java
  3rdParty/libnzmq/src/org/zeromq/ZMQ.java
Labels: bug

#823 Bug fix for sync stats
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncMgr.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/valid/TransactionTypeValidator.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: bug

#824 fix small vulnerablity concerns
  modAionImpl/src/org/aion/zero/impl/config/dynamic/InFlightConfigReceiver.java
  modCrypto/src/org/aion/crypto/hash/Blake2b.java
  modCrypto/src/org/libsodium/jni/crypto/Util.java
Labels: bug

#775 Expand top seeds sync stats
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskStorePendingBlocks.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/BlockPropagationHandler.java
  modAionImpl/test/org/aion/zero/impl/sync/BlockPropagationTest.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: enhancement

#817 Sync State 2: Handler for trie data request messages
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/core/IAionBlockchain.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/RequestTrieDataHandler.java
  modAionImpl/test/mockito-extensions/org.mockito.plugins.MockMaker
  modAionImpl/test/org/aion/zero/impl/sync/handler/RequestTrieDataHandlerTest.java
  modMcf/src/org/aion/mcf/trie/Trie.java
  modMcf/src/org/aion/mcf/trie/TrieImpl.java
  modMcf/src/org/aion/mcf/trie/scan/CollectMappings.java
  modMcf/test/org/aion/mcf/trie/TrieTest.java
  modP2p/src/org/aion/p2p/V1Constants.java
Labels: feature

#818 Sync State 3: Handler for trie data response messages
  modAionImpl/src/org/aion/zero/impl/sync/TrieNodeWrapper.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResponseTrieDataHandler.java
  modAionImpl/test/org/aion/zero/impl/sync/TrieNodeWrapperTest.java
  modAionImpl/test/org/aion/zero/impl/sync/handler/ResponseTrieDataHandlerTest.java
Labels: feature

#829 ZMQ wrapper - add Windows/Mac native libs and loading logic
  .gitignore
  3rdParty/libnzmq/resources/native/darwin/zmq/libjzmq.0.dylib
  3rdParty/libnzmq/resources/native/darwin/zmq/libzmq.5.dylib
  3rdParty/libnzmq/resources/native/linux/zmq/file.list
  3rdParty/libnzmq/resources/native/win/zmq/jzmq.dll
  3rdParty/libnzmq/resources/native/win/zmq/libzmq.dll
  3rdParty/libnzmq/src/org/zeromq/NativeZmqLoader.java
  3rdParty/libnzmq/src/org/zeromq/ZMQ.java
Labels: build script

#826 Enable AVM inside BulkExecuter based on given config
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modVM/src/org/aion/vm/BulkExecutor.java
Labels: bug

#820 Sync State 4: Task for importing trie data
  modAionBase/src/org/aion/base/util/ByteArrayWrapper.java
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modAionImpl/src/org/aion/zero/impl/sync/FastSyncManager.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskImportTrieData.java
  modAionImpl/test/org/aion/zero/impl/db/AionRepositoryImplTest.java
  modAionImpl/test/org/aion/zero/impl/sync/TaskImportTrieDataTest.java
  modAionImpl/test/org/aion/zero/impl/sync/msg/ResponseTrieDataTest.java
  modMcf/src/org/aion/mcf/trie/Trie.java
  modMcf/src/org/aion/mcf/trie/TrieImpl.java
  modMcf/src/org/aion/mcf/trie/TrieNodeResult.java
  modMcf/test/org/aion/mcf/trie/TrieTest.java
Labels: feature

#831 Add -Xmx8g into the launch script
  aion.sh
Labels: enhancement

#832 Seed node config update
  config/mainnet/config.xml
  config/mastery/config.xml
Labels: document change

#830 added more logging info for test harness usage
  modAionImpl/src/org/aion/zero/impl/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionPendingStateImpl.java
Labels: enhancement

#834 peer response sync stats
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetBodies.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetHeaders.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskGetStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResBlocksBodiesHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResBlocksHeadersHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/handler/ResStatusHandler.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/ResponseStats.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/ResponseStatsTracker.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: enhancement, feature

#836 Minor enhancements to stats and kernel use
  config/mainnet/config.xml
  config/mastery/config.xml
  modAionImpl/src/org/aion/zero/impl/AionHub.java
  modAionImpl/src/org/aion/zero/impl/sync/RequestCounter.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncMgr.java
  modAionImpl/src/org/aion/zero/impl/sync/SyncStats.java
  modAionImpl/src/org/aion/zero/impl/sync/TaskShowStatus.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/ResponseStats.java
  modAionImpl/src/org/aion/zero/impl/sync/statistics/ResponseStatsTracker.java
  modAionImpl/test/org/aion/zero/impl/sync/SyncStatsTest.java
Labels: bug, enhancement
