Repository aionnetwork/aion, pull requests merged in 2019-12, with the labels that each got.

#1083 Added archive kernel functional test logs to Jenkins CI
  Jenkinsfile
Labels: build script

#1080 AKI-601 Limit the eth_getLogs can't query more than 1000 blocks
  modApiServer/src/org/aion/api/server/rpc/ApiWeb3Aion.java
  modApiServer/src/org/aion/api/server/types/FltrLg.java
  modApiServer/test/org/aion/api/server/rpc/ApiWeb3AionTest.java
Labels: enhancement

#1084 Rocks DB tune-up
  modAionImpl/src/org/aion/zero/impl/config/CfgDbDetails.java
  modDbImpl/build.gradle
  modDbImpl/src/org/aion/db/impl/DatabaseFactory.java
  modDbImpl/src/org/aion/db/impl/leveldb/LevelDB.java
  modDbImpl/src/org/aion/db/impl/leveldb/LevelDBConstants.java
  modDbImpl/src/org/aion/db/impl/rocksdb/RocksDBConstants.java
  modDbImpl/src/org/aion/db/impl/rocksdb/RocksDBWrapper.java
  modDbImpl/test/org/aion/db/impl/DatabaseFactoryTest.java
  modDbImpl/test/org/aion/db/impl/DatabaseTestUtils.java
  modDbImpl/test/org/aion/db/impl/leveldb/LevelDBDriverTest.java
  modDbImpl/test/org/aion/db/impl/rocksdb/RocksDBDriverTest.java
Labels: enhancement

#1087 Adjusted message receive worker threads to the system avaliable proce…
  modP2pImpl/src/org/aion/p2p/impl1/P2pMgr.java
Labels: enhancement

#1085 Reduced complexity of TaskSend
  modP2pImpl/src/org/aion/p2p/impl1/tasks/TaskSend.java
Labels: enhancement

#1090 Sync Enhancement
  modAionImpl/src/org/aion/zero/impl/sync/SyncHeaderRequestManager.java
Labels: enhancement

#1093 AKI-615: Making the contract info store thread-safe.
  modAionImpl/src/org/aion/zero/impl/db/AionBlockStore.java
  modAionImpl/src/org/aion/zero/impl/db/AionRepositoryImpl.java
  modDbImpl/src/org/aion/db/store/DataSource.java
  modDbImpl/src/org/aion/db/store/DataSourceArray.java
  modDbImpl/src/org/aion/db/store/LockedObjectStore.java
  modDbImpl/src/org/aion/db/store/Stores.java
Labels: bug

#1097 Added reference to The OAN and Open Apps
  README.md
Labels: document change

#1088 Updated the best block info when initializing the self node info call…
  modAionImpl/src/org/aion/zero/impl/blockchain/AionHub.java
Labels: enhancement
