Repository aionnetwork/aion, pull requests merged in 2020-03, with the labels that each got.

#1124 AKI-668 fixes TxPoolV1 ConcurrentModificationException
  modTxPool/src/org/aion/txpool/v1/TxPoolV1.java
  modTxPool/test/org/aion/txpool/v1/TxPoolV1Test.java
Labels: bug

#1123 AKI-669: Correct reset for PoS difficulty on load
  modAionImpl/src/org/aion/zero/impl/blockchain/AionHub.java
Labels: bug

#1126 AKI-672: Call repository close on main instance
  modAionImpl/src/org/aion/zero/impl/blockchain/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/blockchain/AionHub.java
Labels: bug

#1133 Add test for kernel internal shutdown
  modAionImpl/build.gradle
  modAionImpl/test/org/aion/zero/impl/blockchain/StandaloneBlockchainTest.java
Labels: unit tests

#1136 AKI-683 submit the staking block on-time
  modAionImpl/src/org/aion/zero/impl/blockchain/AionBlockchainImpl.java
  modAionImpl/src/org/aion/zero/impl/types/StakingBlock.java
  modAionImpl/src/org/aion/zero/impl/types/StakingBlockHeader.java
  modApiServer/src/org/aion/api/server/http/RpcServer.java
  modApiServer/src/org/aion/api/server/rpc3/AionChainHolder.java
  modApiServer/src/org/aion/api/server/rpc3/ChainHolder.java
  modApiServer/test/org/aion/api/server/rpc3/AionChainHolderTest.java
  modApiServer/test/org/aion/api/server/rpc3/StakingRPCImplTest.java
Labels: enhancement
